### PR TITLE
Add dependencies list to main readme in root.

### PR DESCRIPTION
**Pull request by edfairweather**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@edfairweather__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by bennage** [comment]
Thanks for the contribution and our apologies for not responding faster.
We actually prefer to list the dependencies for each invidual solution rather than for the repo as whole.
Do you think that I note in the root readme saying "see indiviudal readme for dependencies" would be helpful?

**Comment by edfairweather** [comment]
Yes that makes sense.

**Comment by bennage** [comment]
The update was made here 09b4b35c9088f31d5ece3f3475bce564ff83256b

**Pull request closed without merging**
