### PR TITLE
added test recipe for busydatabase

### PR DESCRIPTION
**Pull request by bennage**
As discused in #81.
Does this add value? Should we modify?
Please review @dragon119, @JohnPWSharp , @mj1856 .

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@bennage__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (christb). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by bennage** [comment]
I think that parts of this could be extracted into a common document. 
Or do you think that it's useful to have each one stand alone?

**Comment by dragon119** [comment]
I think it  can add values. Can we add a table of settings with the following items?
Compute (Websites or Cloud service,size, # instance)
Database (edition)
Connection pool size 
Cache (size)
Other load test settings

**Comment by bennage** [comment]
Sure.
________________________________

**Comment by bennage** [comment]
Ok, I've made some updates. Notice that I split it into two docs.
Please review.

**Comment by dragon119** [comment]
I like the way you separated these files. Only thing I want to add ito the table is the test duration.

**Comment by bennage** [comment]
Done. If you like it, feel free to merge. ;-)

**Comment by JohnPWSharp** [comment]
I am working on these now.

Cheers
  JohnS

**Pull request merged**
